import type { PaletteColor } from "../types";

/**
 * Official LEGO solid colors (current production set).
 * Names and RGB values from the Rebrickable color table:
 * https://rebrickable.com/colors/ (names match BrickLink for these colors).
 */
export const LEGO_COLORS: PaletteColor[] = [
  { hex: "#05131d", name: "Black" },
  { hex: "#ffffff", name: "White" },
  { hex: "#a0a5a9", name: "Light Bluish Gray" },
  { hex: "#6c6e68", name: "Dark Bluish Gray" },
  { hex: "#c91a09", name: "Red" },
  { hex: "#720e0f", name: "Dark Red" },
  { hex: "#fe8a18", name: "Orange" },
  { hex: "#a95500", name: "Dark Orange" },
  { hex: "#f8bb3d", name: "Bright Light Orange" },
  { hex: "#f2cd37", name: "Yellow" },
  { hex: "#fff03a", name: "Bright Light Yellow" },
  { hex: "#bbe90b", name: "Lime" },
  { hex: "#dfeea5", name: "Yellowish Green" },
  { hex: "#4b9f4a", name: "Bright Green" },
  { hex: "#237841", name: "Green" },
  { hex: "#184632", name: "Dark Green" },
  { hex: "#73dca1", name: "Medium Green" },
  { hex: "#a0bcac", name: "Sand Green" },
  { hex: "#9b9a5a", name: "Olive Green" },
  { hex: "#b3d7d1", name: "Aqua" },
  { hex: "#008f9b", name: "Dark Turquoise" },
  { hex: "#36aebf", name: "Medium Azure" },
  { hex: "#078bc9", name: "Dark Azure" },
  { hex: "#9fc3e9", name: "Bright Light Blue" },
  { hex: "#5a93db", name: "Medium Blue" },
  { hex: "#0055bf", name: "Blue" },
  { hex: "#0a3463", name: "Dark Blue" },
  { hex: "#6074a1", name: "Sand Blue" },
  { hex: "#e1d5ed", name: "Lavender" },
  { hex: "#ac78ba", name: "Medium Lavender" },
  { hex: "#81007b", name: "Purple" },
  { hex: "#923978", name: "Magenta" },
  { hex: "#c870a0", name: "Dark Pink" },
  { hex: "#e4adc8", name: "Bright Pink" },
  { hex: "#ff698f", name: "Coral" },
  { hex: "#fecccf", name: "Light Pink" },
  { hex: "#e4cd9e", name: "Tan" },
  { hex: "#958a73", name: "Dark Tan" },
  { hex: "#f6d7b3", name: "Light Nougat" },
  { hex: "#d09168", name: "Nougat" },
  { hex: "#aa7d55", name: "Medium Nougat" },
  { hex: "#582a12", name: "Reddish Brown" },
  { hex: "#352100", name: "Dark Brown" },
];
